### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by son-link** [son-link/arkaway#1]
- [ ] Add mouse support
- [ ] Test more speed for ball and paddle
- [ ] Add some sounds effects
- [ ] Add endgame screen
